### PR TITLE
refactor: Use new decky plugin format

### PR DESCRIPTION
**Pull request by eXhumer**
This uses the `aa/websockets` branch of `decky-plugin-template` to use the new plugin format for Decky Loader.

* replace usage of `decky-frontend-lib` with `@decky/api` & `@decky/ui`
* use `@decky/rollup` to do rollup configuration
* upgrade outdated dependencies
* update ci to use pnpm@9 specifically

Tested build to be working on latest Beta (3.6.15) & Release (3.5.19) version of SteamOS with Decky Loader v3.0.1.

### CODE REVIEW

**Comment by eXhumer** [comment]
PS: The changes in `main.py` are changes mainly to stop flake8 complaining about style. The real change in is just to rename `decky_plugin` import to `decky`.

Also, the `classmethod` decorators were added as the methods are not instance method, but class method.

**Comment by eXhumer** [comment]
Also note that the usage of `Backend.bridge` is being replaced with `callable` from `@decky/api`. Inside the `bridge` method, there was a `console.debug(`Calling backend function: ${functionName}`)`, which hasn't been re-introduced with callable.

**Comment by SheffeyG** [comment]
Cool, that's exactly what I planned to do. Maybe you'd be interested in collaborating on this project?

**Comment by eXhumer** [comment]
> @eXhumer Cool, that's exactly what I planned to do. Maybe you'd be interested in collaborating on this project?

Would be happy to do so.

**Comment by SheffeyG** [comment]
@eXhumer Done, you can assign yourself now!

**Comment by eXhumer** [comment]
Thanks. Do you have any changes requested for this PR, or is this OK to merge?

**Comment by SheffeyG** [comment]
Didn't test it yet on my machine, I will do it later.

**Comment by eXhumer** [comment]
Added `eslint` and fixed existing code to keep style across code consistent. Using 2 spaces, double quote, requires semi and uses recommended default style from `eslint`.

**Comment by eXhumer** [comment]
Also added new CI job to lint as well.

**Comment by SheffeyG** [comment]
@eXhumer Did you test this build on SD? It does not load properly on my machine with decky 3.0.1

**Comment by eXhumer** [comment]
> @eXhumer Did you test this build on SD? It does not load properly on my machine with decky 3.0.1

What exactly didn't work. Just tested it again on my Steam Deck and seems like all is working fine on the Beta branch currently.

**Comment by eXhumer** [comment]
https://github.com/eXhumer/CheatDeck/actions/runs/11076759180

Tested using the following artifact.

**Comment by SheffeyG** [comment]
> https://github.com/eXhumer/CheatDeck/actions/runs/11076759180
> 
> Tested using the following artifact.

This build from action works, but if I build it manually with `rollup -c`, the output is
```
md5sum dist/index.js
94d4a374709cd7bb53c8a3b1dd714ca2  dist/index.js
```

 and it says `Failed to fetch dynamically imported module` while loading, should we reconfigure rollup options?

**Comment by eXhumer** [comment]
> > https://github.com/eXhumer/CheatDeck/actions/runs/11076759180
> > Tested using the following artifact.
> 
> This build from action works, but if I build it manually with `rollup -c`, the output is
> 
> ```
> md5sum dist/index.js
> 94d4a374709cd7bb53c8a3b1dd714ca2  dist/index.js
> ```
> 
> and it says `Failed to fetch dynamically imported module` while loading, should we reconfigure rollup options?

Which platform are you using you rollup? It seems to be working for me on Linux and MacOS.

```
➜  CheatDeck git:(main) ✗ pnpm exec rollup -c

./src/index.tsx → dist...
created dist in 1.5s
➜  CheatDeck git:(main) ✗ pnpm exec rollup -v
rollup v4.22.4
```

**Comment by eXhumer** [comment]
Try using `pnpm install && pnpm run build` instead of `rollup -c`.

**Comment by eXhumer** [comment]
Currently, I replaced `@decky/rollup` does the configuration for us. The current rollup config simply import the default export from `@decky/rollup` and exports it directly.

https://github.com/SheffeyG/CheatDeck/blob/1194a714836ce87c666182d5cff855f91447fefe/rollup.config.js#L1-L5

**Comment by SheffeyG** [comment]
I work on win10 WSL, but we use the same pnpm lockfile, so that shouldn't be a problem, and I do run `rollup -c` by `pnpm build`, could you show the outputs md5?
For me it's
```
md5sum dist/index.js
94d4a374709cd7bb53c8a3b1dd714ca2  dist/index.js
```

**Comment by eXhumer** [comment]
```
➜  CheatDeck git:(main) ✗ pnpm run build

> cheatdeck@0.3.2 build /Users/exhumer/Projects/CheatDeck
> rollup -c


./src/index.tsx → dist...
created dist in 1.5s
➜  CheatDeck git:(main) ✗ md5sum dist/index.js
94d4a374709cd7bb53c8a3b1dd714ca2  dist/index.js
```

**Comment by eXhumer** [comment]
Even the `dist/index.js` from the artifact hash the same hash.

**Comment by eXhumer** [comment]
Can you `rm -rf node_modules` and do the installation step again in the environment that you are trying to build from. decky cli fails for me on MacOS if I don't delete the node_modules before building the plugin due to dependency issue.

```
➜  CheatDeck git:(main) ✗ ./cli/decky plugin build .
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
INFO [decky::plugin] Looking for package.json...
INFO [decky::plugin] Looking for plugin.json...
INFO [decky::plugin] Looking for deck.json...
INFO [decky::cli::plugin::build] Creating temporary build directory
INFO [decky::cli::plugin::build] Building plugin
INFO [decky::cli::plugin::build] Plugin does not have a custom backend
INFO [decky::cli::plugin::build] Building frontend
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Line: ? The modules directory at "/plugin/node_modules" will be removed and reinstalled from scratch. Proceed? (Y/n) ‣ true
Line:    ╭──────────────────────────────────────────────────────────────────╮
Line:    │                                                                  │
Line:    │                Update available! 9.4.0 → 9.11.0.                 │
Line:    │   Changelog: https://github.com/pnpm/pnpm/releases/tag/v9.11.0   │
Line:    │                Run "pnpm add -g pnpm" to update.                 │
Line:    │                                                                  │
Line:    │         Follow @pnpmjs for updates: https://x.com/pnpmjs         │
Line:    │                                                                  │
Line:    ╰──────────────────────────────────────────────────────────────────╯
Line:
Line:
Line: > cheatdeck@0.3.2 build /plugin
Line: > rollup -c
Line:
/plugin/node_modules/.pnpm/rollup@4.22.5/node_modules/rollup/dist/native.js:59
		throw new Error(
		^

Error: Cannot find module @rollup/rollup-linux-x64-musl. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (/plugin/node_modules/.pnpm/rollup@4.22.5/node_modules/rollup/dist/native.js:59:9)
    at Object.<anonymous> (/plugin/node_modules/.pnpm/rollup@4.22.5/node_modules/rollup/dist/native.js:68:76)
    ... 3 lines matching cause stack trace ...
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/plugin/node_modules/.pnpm/rollup@4.22.5/node_modules/rollup/dist/shared/parseAst.js:12:19)
    at Module._compile (node:internal/modules/cjs/loader:1358:14) {
  [cause]: Error: Cannot find module '@rollup/rollup-linux-x64-musl'
  Require stack:
  - /plugin/node_modules/.pnpm/rollup@4.22.5/node_modules/rollup/dist/native.js
  - /plugin/node_modules/.pnpm/rollup@4.22.5/node_modules/rollup/dist/shared/parseAst.js
  - /plugin/node_modules/.pnpm/rollup@4.22.5/node_modules/rollup/dist/shared/rollup.js
  - /plugin/node_modules/.pnpm/rollup@4.22.5/node_modules/rollup/dist/bin/rollup
      at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
      at Module._load (node:internal/modules/cjs/loader:986:27)
      at Module.require (node:internal/modules/cjs/loader:1233:19)
      at require (node:internal/modules/helpers:179:18)
      at requireWithFriendlyError (/plugin/node_modules/.pnpm/rollup@4.22.5/node_modules/rollup/dist/native.js:41:10)
      at Object.<anonymous> (/plugin/node_modules/.pnpm/rollup@4.22.5/node_modules/rollup/dist/native.js:68:76)
      at Module._compile (node:internal/modules/cjs/loader:1358:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
      at Module.load (node:internal/modules/cjs/loader:1208:32)
      at Module._load (node:internal/modules/cjs/loader:1024:12) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/plugin/node_modules/.pnpm/rollup@4.22.5/node_modules/rollup/dist/native.js',
      '/plugin/node_modules/.pnpm/rollup@4.22.5/node_modules/rollup/dist/shared/parseAst.js',
      '/plugin/node_modules/.pnpm/rollup@4.22.5/node_modules/rollup/dist/shared/rollup.js',
      '/plugin/node_modules/.pnpm/rollup@4.22.5/node_modules/rollup/dist/bin/rollup'
    ]
  }
}

Node.js v20.15.0
Line:  ELIFECYCLE  Command failed with exit code 1.
Line: error code: 0
Line: pnpm build failed, please report this issue to the CI maintainer and the plugin developer.
Error: Failed to build frontend. There might be more information in the output above.

Caused by:
    child status was: exit status: 1
➜  CheatDeck git:(main) ✗
```

**Comment by SheffeyG** [comment]
> Even the `dist/index.js` from the artifact has the same hash.

Oops, I made a mistake take other build's hash as this ones, there's no problem with the build process, I guess I forgot add `api_version` to plugin.json or something else, anyway it works fine after a reboot and reinstall from zip file. Lets merge this!

**Pull request merged**
