### PR TITLE
feat: add multilingual support

### PR DESCRIPTION
**Pull request by SheffeyG**
[WIP]
If you are willing to help translate CheatDeck to your language, please reference `src/data/i18n/en.json` make a translated file with a name like `xx-xx.json` and submit it to this branch `i18n`.

### CODE REVIEW

**Comment by SheffeyG** [comment]
@eXhumer Could you take a look at this en.json file? it's for other translator referencing, so any changes or polish is good.

**Comment by eXhumer** [comment]
Thoughts on loading the translation JSONs dynamically instead of bundling them with rollup?

I was thinking maybe the translation files should go into the defaults folder, but I realized that they are imported at compile time.

**Review by eXhumer — APPROVED** [review]
LGTM

**Comment by SheffeyG** [comment]
> Thoughts on loading the translation JSONs dynamically instead of bundling them with rollup?

I tried that, but dynamic import means all async, I don't wanne do that. unless you get better idea?

**Comment by eXhumer** [comment]
True, not sure if there is any point or difference anyways.

**Comment by SheffeyG** [comment]
I once wrote that
```py
const languages: Languages = {
  en: require("../data/i18n/en.json"),
  zhCn: require("../data/i18n/zh-cn.json"),
};
```
so we don't have to impoort each json then construct them all in `languages`, but we cant use require to import, not ES style I guess.

**Comment by eXhumer** [comment]
I have looked into how to best integrate Crowdin and I think we should follow in the direction of how MetaDeck have set it up.

https://github.com/EmuDeck/MetaDeck/blob/main/crowdin.yaml
https://github.com/EmuDeck/MetaDeck/tree/main/src/ts/localisation
https://github.com/EmuDeck/MetaDeck/blob/main/src/ts/translations.ts

We can use a similar setup to integrate it into CheatDeck as well. Let me know if you think it is a good idea, and I'll look into setting up a Crowdin project.

**Comment by SheffeyG** [comment]
@eXhumer I experimented with Crowdin, and while it's practical for large projects, but cheatdeck is such a tiny project with only 30 strings needing translation, I prefer pre-translate it with a little help from LLM, so anyone who wants to help with translations can do so without creating any crowdin account.

**Pull request merged**
