### PR TITLE
chore: Update README

### PR DESCRIPTION
**Pull request by eXhumer**
* add license and nightly build status badges
* add information about how to download latest nightly

GitHub Actions artifact download requires authentication, [nightly.link](https://nightly.link/) bypasses this requirement.

### CODE REVIEW

**Comment by eXhumer** [comment]
Clicking on the `nightly build` shield will download the latest nightly build directly and clicking on `license` shield will open the project license from GitHub.

**Comment by SheffeyG** [comment]
There was a query api to show the download number from decky store: 
https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fplugins.deckbrew.xyz%2Fplugins&query=%24%5B%3F(%40.name%20%3D%3D%20%27CheatDeck%27)%5D.downloads&suffix=%20installs&label=decky&color=3ea6a3
unfortunately, this shield stop work recently.

**Comment by eXhumer** [comment]
`ShieldsBadge].downloads)` for testing store download number.

`ShieldsBadge].downloads)` for release store download number.

See later if we are ever able to get this working.

Updated link for Decky Loader, moved images into collapsible section and added note regarding what to do if a selected trainer or program doesn't run with the game.

**Comment by eXhumer** [comment]
I was able to get the download numbers working, it will now show the numbers from both testing store and release store (when available).

**Pull request merged**
